version: "3.7"

services:
  backend:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/home/app/web/*
    ports:
      - 8000:8000
    environment:
      - DEBUG=1
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=hello_django_dev
      - SQL_USER=hello_django
      - SQL_PASSWORD=hello_django
      - SQL_HOST=db
      - SQL_PORT=5432
    depends_on:
      - db
  frontend:
    build: ./frontend
    command: npm start
    volumes:
      - "./frontend:/app"
      - "/app/node_modules"
    ports:
      - "3000:3000"
      - "35729:25729"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

volumes:
  postgres_data:
